libraries: # This is called out once within the config.yml file
  4k-Movies: &movie_config
    settings: &kometa_settings
      asset_directory: /assets/4k-Movies
      prioritize_assets: true
    run_order: &run_order
    - collections
    - metadata
    - operations
    - overlays
    template_variables:
      sep_style: gray # use the gray separators globally for this library
      collection_mode: show # hide the collections
      language: en # could be default(which is en), da, de, fr, pt-br or another lang code that we have translated
      placeholder_imdb_id: tt8579674 # 1917 (2019) placeholder id for the separators
    collection_files: &movie_collections
      - file: /config/custom/movie_subgenre.yml
      - default: based # collections based on a book, comic, story, video game
      - default: separator_award # An "index card"
      - default: pca # People's Choice Awards
      - default: sag # Screen Actors Guild Awards
      - default: tiff # Toronto International Film Festival Awards
      - default: bafta # BAFTA Awards
      - default: cannes # Cannes Film Festival Awards
      - default: choice # Critic's Choice Awards
      - default: emmy # Emmy Awards
      - default: golden # Golden Globes Awards
      - default: oscars # The Oscars
      - default: spirit # Independent Spirit Awards
      - default: sundance # Sundance Film Festival Awards
      - default: separator_chart # An "index card"
      - default: imdb # IMDb Charts (Popular, Trending, etc.)
      - default: myanimelist # MAL Charts (Popular, Trending, etc.)
      - default: other_chart # Other Charts (Popular, Trending, etc.)
      - default: tautulli # Tautulli Charts (Popular, Trending, etc.)
      - default: tmdb # TMDb Charts (Popular, Trending, etc.)
      - default: trakt # Trakt Charts (Popular, Trending, etc.)
      - default: basic # Some basic chart collections based on recently released media in your library
      - default: collectionless # Collectionless collection to help Show/Hide Movies/Shows properly in your library
      - default: actor
        template_variables:
          collection_section: "001"
          use_separator: false
          style: diiivoycolor
          name_format: 🎂 <<key_name>>'s Birthday
          translation_key: birthday
          sort_by: audience_rating.desc
          title_format: <<key_name>>'s Birthday
          data:
            depth: 20
            limit: 100
          tmdb_birthday:
            this_month: true
      - default: actor # Actors
        template_variables: # bw, rainier, diiivoy, diiivoycolor, or orig style is used.
          style: signature
          data:
            depth: 1
            limit: 15
      - default: director # Directors
        template_variables: # bw, rainier, diiivoy, diiivoycolor, or orig style is used.
          style: signature
          data:
            depth: 1
            limit: 15
      - default: producer # Producers
        template_variables: # bw, rainier, diiivoy, diiivoycolor, or orig style is used.
          style: signature
          data:
            depth: 1
            limit: 15
      - default: writer # Writers
        template_variables: # bw, rainier, diiivoy, diiivoycolor, or orig style is used.
          style: signature
          data:
            depth: 1
            limit: 15
      - default: genre # Action, Comedy, Drama, etc.
      - default: studio # DreamWorks Studios, Lucasfilm Ltd, etc.
      - default: decade # Decade the media item was released
      - git: bullmoose20/separator_franchise # Separator for franchise
        template_variables:
          collection_section: "035" # Set to "035" to be right before universe. Should be the same here and below
      - default: franchise # https://kometa.wiki/en/latest/defaults/movie/franchise
        template_variables:
          collection_section: "035" # Set to "035" to be right before universe. Should be the same here and above
      - default: seasonal # Christmas, Halloween, etc.
        template_variables:
          schedule_years: daily # Keep as daily unless specific year-end/new-year range is desired
          schedule_valentine: range(02/01-02/14) # First half of February
          schedule_patrick: range(03/01-03/17) # First half of March up to St. Patrick's Day
          schedule_easter: range(03/15-04/15) # Covers typical Easter timeframe (late March - mid April)
          schedule_mother: range(05/01-05/15) # First half of May for Mother's Day
          schedule_memorial: range(05/15-05/31) # Second half of May for Memorial Day
          schedule_father: range(06/01-06/21) # First three weeks of June for Father's Day
          schedule_independence: range(07/01-07/07) # Week of July 4th
          schedule_labor: range(09/01-09/10) # Early September for Labor Day
          schedule_halloween: range(10/15-10/31) # Second half of October for Halloween
          schedule_veteran: range(11/01-11/11) # Early November up to Veteran's Day
          schedule_thanksgiving: range(11/15-11/30) # Second half of November for Thanksgiving (US)
          schedule_christmas: range(12/01-12/25) # December leading up to Christmas
          schedule_aapi: range(05/01-05/31) # AAPI Heritage Month (May)
          schedule_disabilities: range(07/01-07/31) # Disability Pride Month (July)
          schedule_black_history: range(02/01-02/28) # Black History Month (February)
          schedule_lgbtq: range(06/01-06/30) # LGBTQ+ Pride Month (June)
          schedule_latinx: range(09/15-10/15) # Latinx Heritage Month (Mid-Sep to Mid-Oct)
          schedule_women: range(03/01-03/31) # Women's History Month (March)
      - default: streaming # Streaming on Disney+, Netflix, etc.
      - default: universe # Marvel Cinematic Universe, Wizarding World, etc.
    overlay_files: &movie_overlays
    - file: /config/overlays/media_info.yml
      template_variables:
        use_gradient_top: false
        use_gradient_bottom: false
    - file: /config/overlays/audience_rating.yml
    - default: mediastinger
      template_variables:
        vertical_offset: 50
    - default: runtimes
      template_variables:
        vertical_offset: 37
        horizontal_align: center
        horizontal_offset: 140
        text: ''
        back_width: 205
        back_color: '#00000000'
    - remove_overlays: false
    operations:
    - &id001
      schedule: daily
      split_duplicates: false   # Splits all duplicate movies/shows found in this library
      assets_for_all: true   # Search in assets for images for every item in your library
      delete_collections:
        configured: false   # False - Collection must be an Unconfigured Collection to be deleted (collection is not in the config file of the specific Kometa run).
        managed: false   # False - Collection must be an Unmanaged Collection to be deleted (the collection does not have the Kometa label)
        less: 99999   # Effectively all collections regardless of the number of items in the collection
    - &id002
      schedule: Weekly (monday)
      mass_user_rating_update: mdb_tomatoes
    - &id003
      schedule: Weekly (tuesday)
      mass_critic_rating_update: imdb
    - &id004
      schedule: Weekly (wednesday)
      mass_audience_rating_update: tmdb
    - &id005
      schedule: yearly(01/01)
      mass_genre_update:
      - tmdb     # Update all genres from tmdb
      - imdb     # Update all genres from imdb if not from tmdb
      - tvdb     # Update all genres from tvdb if not from imdb
    - &id006
      schedule: Weekly (friday)
      mass_content_rating_update:
      - mdb_commonsense     # Changes Content Rating to "1", "2" etc. to specify appropriate age
      - omdb     # Changes Content Rating from omdb if not found on mdb_commonsense
    - &id007
      schedule: Weekly (saturday)
      mass_studio_update:
      - tmdb
      - tvdb
      - omdb     # Update all studios from tmdb
    - &id008
      schedule: Weekly (sunday)
      mass_originally_available_update:
      - tmdb     # Update all original available date from tmdb
      - tvdb     # Update all original available date from tvdb if not from tmdb
      - omdb     # Update all original available date from omdb(imdb) if not from tvdb
    minimum_items: &minimum_items 1
    radarr: &radarr
      url: <<RADARR_UHD_HOST>>
      token: <<RADARR_UHD_API_KEY>>
      add_missing: false
      add_existing: true
      root_folder_path: <<RADARR_UHD_ROOT_FOLDER_PATH>>
      monitor: true
      monitor_existing: true
      ignore_cache: false
      availability: announced
      quality_profile: UHD Bluray + WEB
  Movies:
    <<: *movie_config
    settings:
      <<: *kometa_settings
      asset_directory: /assets/Movies
    radarr:
      <<: *radarr
      url: <<RADARR_HOST>>
      token: <<RADARR_API_KEY>>
      root_folder_path: <<RADARR_ROOT_FOLDER_PATH>>
      quality_profile: HD Bluray + WEB
  4k-TV Shows: &tv_config
    settings:
      <<: *kometa_settings
      asset_directory: /assets/4k-TV Shows
    run_order: *run_order
    template_variables:
      sep_style: gray # use the gray separators globally for this library
      collection_mode: show # hide the collections
      language: en # could be default(which is en), da, de, fr, pt-br or another lang code that we have translated
      placeholder_imdb_id: tt1190634 # The Boys (2019) placeholder id for the separators
    collection_files: # These files contain collections: and/or dynamic_collections attributes
      - default: based # collections based on a book, comic, story, video game
      - default: aspect # Creates collections based on aspect ratio of media item
      - git: bullmoose20/tv_refresh # Tells plex to refresh media items added within the last 7 days
      - default: separator_award # An "index card"
      - default: pca # People's Choice Awards
      - default: choice # Critic's Choice Awards
      - default: golden # Golden Globes Awards
      - default: emmy # Emmy Awards
      - default: separator_chart # An "index card"
      - default: anilist # AniDB Charts (Popular, Trending, etc.)
      - default: imdb # IMDb Charts (Popular, Trending, etc.)
      - default: myanimelist # MAL Charts (Popular, Trending, etc.)
      - default: other_chart # Other Charts (Popular, Trending, etc.)
      - default: tautulli # Tautulli Charts (Popular, Trending, etc.)
      - default: tmdb # TMDb Charts (Popular, Trending, etc.)
      - default: trakt # Trakt Charts (Popular, Trending, etc.)
      - default: basic # Some basic chart collections based on recently released media in your library
      - default: collectionless # Collectionless collection to help Show/Hide Movies/Shows properly in your library
      - default: actor
        template_variables:
          collection_section: "001"
          use_separator: false
          style: diiivoycolor
          name_format: 🎂 <<key_name>>'s Birthday
          translation_key: birthday
          sort_by: audience_rating.desc
          title_format: <<key_name>>'s Birthday
          data:
            depth: 20
            limit: 100
          tmdb_birthday:
            this_month: true
      - default: actor # Actors
        template_variables: # bw, rainier, diiivoy, diiivoycolor, or orig style is used. 
          style: signature
          data:
            depth: 1
            limit: 15
      - default: genre # Action, Comedy, Drama, etc.
      - default: studio # DreamWorks Studios, Lucasfilm Ltd, etc.
      - default: decade # Decade the media item was released
      - git: bullmoose20/separator_franchise # Separator for franchise
        template_variables:
          collection_section: "035" # Set to "035" to be right before universe. Should be the same here and below
      - default: franchise # https://kometa.wiki/en/latest/defaults/movie/franchise
        template_variables:
          collection_section: "035" # Set to "035" to be right before universe. Should be the same here and above
      - default: network # ABC, CBC, NBC, FOX, etc.
      - default: streaming # Streaming on Disney+, Netflix, etc.
      - default: universe # Marvel Cinematic Universe, Wizarding World, etc.
    overlay_files:
    - file: /config/overlays/media_info.yml
      template_variables:
        video_only: true
        use_gradient_top: false
        use_gradient_bottom: false
    - file: /config/overlays/audience_rating.yml
    - default: status
      template_variables:
        horizontal_align: center
        vertical_align: bottom
        vertical_offset: 23
        horizontal_offset: 0
        back_height: 149
        back_width: 965
        font: /config/overlays/fonts/Colus-Regular.ttf
        font_size: 60
        font_color_airing: '#27C24C'
        font_color_returning: '#FFA500'
        font_color_canceled: '#ED1F1F'
        font_color_ended: '#FF0000'
        back_color: '#00000000'
    - default: runtimes
      template_variables:
        builder_level: episode
        horizontal_align: right
        back_color: '#00000000'
        back_height: 80
        vertical_offset: 20
        horizontal_offset: 18
        text: ''
        back_width: 205
    - remove_overlays: false
    minimum_items: *minimum_items
    operations:
      <<: [*id001, *id002, *id003, *id004, *id005, *id006, *id007, *id008]
    sonarr: &sonarr
      url: <<SONARR_UHD_HOST>>
      token: <<SONARR_UHD_API_KEY>>
      add_missing: false
      add_existing: true
      root_folder_path: <<SONARR_UHD_ROOT_FOLDER_PATH>>
      monitor: all
      quality_profile: WEB-2160p
      language_profile: English
      series_type: standard
      season_folder: true
  TV Shows:
    <<: *tv_config
    settings:
      <<: *kometa_settings
      asset_directory: /assets/TV Shows
    sonarr:
      <<: *sonarr
      url: <<SONARR_HOST>> 
      token: <<SONARR_API_KEY>>
      root_folder_path: <<SONARR_ROOT_FOLDER_PATH>>
      quality_profile: WEB-1080p

settings:
  cache: true
  cache_expiration: 60
  asset_directory: /assets
  asset_folders: true
  create_asset_folders: true
  asset_depth: 0
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  missing_path: /config/missing
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: true
  only_filter_missing: false
  save_report: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_exclude_users:
    run_order:
    - operations
    - metadata
    - collections
    - overlays
  overlay_artwork_quality: 85
  overlay_artwork_filetype: jpg
  playlist_report: false
  verify_ssl: true
  check_nightly: false
  show_unconfigured: true
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  show_unfiltered: false
  custom_repo:
plex:
  url: <<PLEX_HOST>>
  token: <<PLEX_API_KEY>>
  timeout: 60
  db_cache: 4096
  clean_bundles: true
  empty_trash: true
  optimize: false
  verify_ssl: false
tmdb: 
  apikey: <<TMDB_API_KEY>>
  language: en
  cache_expiration: 60
  region:
tautulli:
  url: <<TAUTULLI_HOST>>
  apikey: <<TAUTULLI_API_KEY>>
omdb:
  apikey: <<OMDB_API_KEY>>
  cache_expiration: 60
mdblist:
  apikey: <<MDBLIST_API_KEY>>
  cache_expiration: 60
trakt:
  client_id: <<TRAKT_CLIENT_ID>>
  client_secret: <<TRAKT_CLIENT_SECRET>>
  authorization:
    access_token: <<TRAKT_ACCESS_TOKEN>>
    token_type: Bearer
    expires_in: <<TRAKT_EXPIRES_IN>>
    refresh_token: <<TRAKT_REFRESH_TOKEN>>
    scope: public
    created_at: <<TRAKT_CREATED_AT>>
  pin:
# notifiarr:
#   API_KEY: <<NOTIFIARR_API_KEY>>
